server:
  port: 19001
  tomcat:
    uri-encoding: UTF-8

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: producer-group
    #同步发送重试次数
    retry-times-when-send-failed: 2
    #异步发送重试次数
    retry-times-when-send-async-failed: 2
